FROM public.ecr.aws/lambda/python:3.9

# Install gcc
RUN yum -y update
RUN yum -y install gcc

# Install the function's dependencies using file requirements.txt
# from your project folder.

COPY lariat_agents/agent/athena/requirements.txt  .
RUN pip3 install --upgrade pip
RUN pip3 install --trusted-host pypi.python.org -r requirements.txt --target "${LAMBDA_TASK_ROOT}"


# Copy function code
COPY lariat_agents/agent/athena ${LAMBDA_TASK_ROOT}/lariat_agents/agent/athena
COPY lariat_agents/base ${LAMBDA_TASK_ROOT}/lariat_agents/base
COPY lariat_agents/sink ${LAMBDA_TASK_ROOT}/lariat_agents/sink
COPY lariat_agents/constants.py ${LAMBDA_TASK_ROOT}/lariat_agents/

COPY ./lariat_python_common ${LAMBDA_TASK_ROOT}/lariat_python_common

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lariat_agents.agent.athena.athena_aws_lambda_executor.lambda_handler" ]