FROM python:3.10-slim

# Install gcc
RUN apt -y update
RUN apt -y install gcc

RUN apt -y install libmagic-dev

WORKDIR /code
COPY ./lariat_agents/agent/event_payload/requirements_gcs.txt /code/requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install --trusted-host pypi.python.org -r requirements.txt

# Copy function code
COPY lariat_agents/agent/event_payload lariat_agents/agent/event_payload
COPY lariat_agents/base lariat_agents/base
COPY lariat_agents/agent/event_payload/shapefiles shapefiles

COPY lariat_agents/sink lariat_agents/sink
COPY lariat_agents/constants.py lariat_agents/

COPY ./lariat_python_common lariat_python_common
ENV PYTHONPATH=/code

CMD ["python", "lariat_agents/agent/event_payload/event_payload_gcp_executor.py"]
#CMD ["uvicorn", "lariat_agents.agent.event_payload.event_payload_gcp_executor:app", "--host", "0.0.0.0", "--port", "80"]