name: Push to ECR us-east-1

on:
  workflow_dispatch

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::358681817243:role/GithubActionsECRProdPushRole
        aws-region: us-east-1
    - name: Amazon ECR "Login" Action for GitHub Actions
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
    - name: Build and push the Docker image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: lariat-snowflake-agent
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build . --platform=linux/amd64 --file lariat_agents/agent/snowflake/Dockerfile_aws --tag $REGISTRY/$REPOSITORY:$IMAGE_TAG --tag $REGISTRY/$REPOSITORY:latest
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:latest
