name: Run tests on PR
on: push
env:
  CLOUD_AGENT_CONFIG_PATH: "test_lariat_bucket/test_cloud_agent_config_path.json"
jobs:
  build:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements_test.txt

      - name: Run Unit Tests
        run: pytest -s -v -m "not integration"

      - name: Run Integration Tests
        run: pytest -s -v -m integration